### ISSUE TITLE
multi-process bug in pool2?

### ISSUE THREAD

**Issue by zacronos** [myndzi/pool2#13]
Apologies for the double-post (I gave some details of this issue as a comment on https://github.com/tgriesser/knex/issues/842), but I realized afterward that my issue is likely separate.

I can reliably get a `Knex:Error Pool2 - Error: Pool.release(): Resource not member of pool` error when running my code with 2 worker processes (via the node `cluster` module).  The error appears to go away when I run with only a single process, however.  Is there any chance there is bug making pool2 unsafe for multi-process?

I am happy to provide `DEBUG=pool2` logs, however they are too large to paste inline.  I'd be happy to email them to you or something like that, though.

**Comment by myndzi** [comment]
Node doesn't use threads, so thread-safety is not a thing: the cluster module spawns worker processes, each being its own instance of node, and they do not share resources (except http request socket handles, which get passed through IPC from the parent which owns the listening socket to the child workers).

I can't see any reason pool2 could be the cause of this error, given that it contains no singletons and only exports classes that get instantiated by consumers. My best guess is that the problem lies somewhere in knex, so I'll continue the conversation over there.
