### ISSUE TITLE
Add "Keep-Alive" or an allocated ping 

### ISSUE THREAD

**Issue by gkorland** [myndzi/pool2#22]
Many of the DBs close idle connections after a predefined time and many times connections can be closed due to temp network disconnection.

The current "ping" mechanism only ping the resource before it's acquired. Adding away to set time interval to ping unallocated resources can help keeping the pool resource alive and clean "dead" resources.

**Comment by myndzi** [comment]
You can simply set 'min' to 0 and assign an idle timeout to reap idle connections rather than attempt to leave them open. As for network interruptions, I don't feel like periodically pinging idle resources is any likelier to discover those than simply attempting to use the resource. Note that if a resource allocation fails, the _request_ that generated it does not necessarily fail -- if the ping fails, a new resource can be allocated and served to the request, rather than failing immediately as a result of the underlying network error (that's what the 'ping' feature is intended for).

I'm not sure periodically pinging the resources adds enough to be worth the extra complexity. Given this information, what do you think now?

Edit: also, when a database closes a resource, it should be automatically removed from the pool; this depends on the code utilizing pool2 to react to and correctly act on that event, of course.

**Comment by myndzi** [comment]
Closing pending a compelling reason to implement

**Comment by gkorland** [comment]
@myndzi "also, when a database closes a resource, it should be automatically removed from the pool;" How do I do it? I didn't see any way to notify the pool a resource is not valid any more, but using the ping, which is a waste cause we can clean the resource earlier and make sure the pool will replace it with a new resource.

As for my original point:
"simply set 'min' to 0 and assign an idle timeout to reap idle connections" - that will yell a bad performance for the first connection request after the pool was "zeroed", keeping the pool "warmed" with a minimum set of resources is critical for the SLA.
