### ISSUE TITLE
Return actual error when acquiring fails

### ISSUE THREAD

**Issue by jaulz** [myndzi/pool2#32]
Any idea if it is possible to pass on the actual error that was raised while acquiring a resource? If bailAfter = 0, the error "pool was destroyed" is returned. If bailAfter = Infiinity, the error "ResourceRequest timed out" is returned. My current work around is to set a listener to "error" on the pool and get the first error. However, I fear that it will produce errors in case of parallel requests.

Thanks for any hint!

**Comment by myndzi** [comment]
You are doing it as correctly as can be done, I think. The problem is that resource requests are resilient -- they aren't tied directly to an upstream request. You might have a situation where, for example, you request a resource from the pool, receive a stale resource that causes an error, then a new one is opened up and served to your request. Should that be an error? After all, it succeeded in the end...

So, yeah, an error or warn listener is your best approach to getting info about things that fail as far as the resource pool2 is managing. You could also do something more directly in the callbacks you specify.

It sounds like there's a network problem connecting to your resource (timed out); bailAfter controls how long to wait until essentially assuming your configuration is incorrect and getting noisy. If no successful requests are served since startup within bailAfter milliseconds, it destroys the pool and all requests will fail instantly with that message.

**Comment by myndzi** [comment]
Gonna close unless you have anything further, but feel free to comment/reopen!
